### ISSUE TITLE
Support generating counter values

### ISSUE THREAD

**Issue by ali786XI** [elastic/elastic-integration-corpus-generator-tool#124]
As of now, the `corpus-generator-tool` produces different `gauge` values with the use of `ranges`, `enum` and `fuzziness` as per the config [documentation](https://github.com/elastic/elastic-integration-corpus-generator-tool/blob/main/docs/fields-configuration.md).

However there can be a config defining a particular field as `counter` so it always produces incremental values. There are many such packages which are TSDB migrated which are using these `counter` [fields](https://github.com/elastic/integrations/blob/main/packages/apache_spark/data_stream/driver/fields/fields.yml#L24). It would be easier to implement the `rally` benchmarking templates as well.

- [ ] Counter support with no reset ([PR](https://github.com/elastic/elastic-integration-corpus-generator-tool/pull/129))
- [ ] Support for counter reset

Counters can be reset:
1. having the possibility to enable/disable just totally random occurrences of the reset.
2. having the possibility to define the probability that the counter is reset every time a new value is generated
3. having the possibility to specify the number of events after which the counter must be reset

Proposal for a `counter_reset` configuration.
```
1. 
counter_reset: 
  strategy: random
2.
counter_reset: 
  strategy: probability
  probability: 0-100 # %
3.
counter_reset: 
  strategy: events_amount
  events_amount: N
```

cc:- @aspacca
