### ISSUE TITLE
Values tending to the minimum value when providing `fuzziness` config

### ISSUE THREAD

**Issue by aliabbas-elastic** [elastic/elastic-integration-corpus-generator-tool#127]
- While generating the corpus of events in the Nginx `stubstatus` data stream, I am seeing the value of a field being set as the minimum value of the `range` provided after a certain set of documents.

Attaching the configs used:-

**config.yml**
```
fields:
  - name: 'timestamp'
    period: -24h # one day
  - name: agent.id
    value: "ef5e274d-4b53-45e6-943a-a5bcf1a6f523"
  - name: service.address
    enum: ["elastic-package-service-nginx-1","elastic-package-service-nginx-2","elastic-package-service-nginx-3"]
  - name: event.duration
    range:
      min: 1
      max: 1000
  - name: writing
    range:
      min: 1
      max: 100
    fuzziness: 0.6
```

Attaching the subset corpus generated for 200 events generated. Find the field `writing` in the corpus generated and it's values generated after a certain set of documents generated. 

```
{    "@timestamp": "2024-01-10T21:38:23.410Z",    "agent": {        "ephemeral_id": "ivorybite",        "id": "ef5e274d-4b53-45e6-943a-a5bcf1a6f523",        "name": "zincbow",        "type": "metricbeat",        "version": "8.8.0"    },    "data_stream": {        "dataset": "nginx.stubstatus",        "namespace": "ep",        "type": "metrics"    },    "ecs": {        "version": "8.5.1"    },    "elastic_agent": {        "id": "ivorybite",        "snapshot": false,        "version": "8.8.0"    },    "event": {        "agent_id_status": "verified",        "dataset": "nginx.stubstatus",        "duration": 58,        "module": "nginx"    },     "host": {        "architecture": "x86_64",        "containerized": false,        "hostname": "docker-fleet-agent",        "id": "66392b0697b84641af8006d87aeb89f1",        "ip": [            "172.18.0.7"        ],        "mac": [            "02-42-AC-12-00-07"        ],        "name": "docker-fleet-agent",        "os": {            "codename": "focal",            "family": "debian",            "kernel": "5.15.49-linuxkit",            "name": "Ubuntu",            "platform": "ubuntu",            "type": "linux",            "version": "20.04.5 LTS (Focal Fossa)"        }    },    "metricset": {        "name": "stubstatus",        "period": 10000    },    "nginx": {        "stubstatus": {            "writing": 1        }    },    "service": {        "address": "http://elastic-package-service-nginx-3:80/server-status",        "type": "nginx"    }}
```
```
{    "@timestamp": "2024-01-10T21:45:35.410Z",    "agent": {        "ephemeral_id": "chestnutpanther",        "id": "ef5e274d-4b53-45e6-943a-a5bcf1a6f523",        "name": "rattleoriole",        "type": "metricbeat",        "version": "8.8.0"    },    "data_stream": {        "dataset": "nginx.stubstatus",        "namespace": "ep",        "type": "metrics"    },    "ecs": {        "version": "8.5.1"    },    "elastic_agent": {        "id": "chestnutpanther",        "snapshot": false,        "version": "8.8.0"    },    "event": {        "agent_id_status": "verified",        "dataset": "nginx.stubstatus",        "duration": 472,        "module": "nginx"    },     "host": {        "architecture": "x86_64",        "containerized": false,        "hostname": "docker-fleet-agent",        "id": "66392b0697b84641af8006d87aeb89f1",        "ip": [            "172.18.0.7"        ],        "mac": [            "02-42-AC-12-00-07"        ],        "name": "docker-fleet-agent",        "os": {            "codename": "focal",            "family": "debian",            "kernel": "5.15.49-linuxkit",            "name": "Ubuntu",            "platform": "ubuntu",            "type": "linux",            "version": "20.04.5 LTS (Focal Fossa)"        }    },    "metricset": {        "name": "stubstatus",        "period": 10000    },    "nginx": {        "stubstatus": {            "writing": 1        }    },    "service": {        "address": "http://elastic-package-service-nginx-2:80/server-status",        "type": "nginx"    }}
```
